@startgantt
'https://plantuml.com/gantt-diagram

'[Prototype design] lasts 13 days and is colored in Lavender/LightBlue
'[Test prototype] lasts 9 days and is colored in Coral/Green and starts 3 days after [Prototype design]'s end
'[Write tests] lasts 5 days and ends at [Prototype design]'s end
'[Hire tests writers] lasts 6 days and ends at [Write tests]'s start
'[Init and write tests report] is colored in Coral/Green
'[Init and write tests report] starts 1 day before [Test prototype]'s start and ends at [Test prototype]'s end
'Project starts 2020-07-01
'[Prototype design] starts 2020-07-01
'[Test prototype] starts 2020-07-16
<style>
ganttDiagram {
	task {
		FontName 나눔스퀘어 bold
		'FontColor red
		FontSize 12
            Padding 4
		'FontStyle bold
		BackGroundColor #DEECFC/#B9CEEB
		LineColor #87A8D0
	}
	timeline{
	    BackGroundColor #DEECFC
	}
'	milestone {
'		FontColor blue
'		FontSize 25
'		FontStyle italic
'		BackGroundColor yellow
'		LineColor red
'	}
'	note {
'		FontColor DarkGreen
'		FontSize 10
'		LineColor OrangeRed
'	}
'	arrow {
'		FontName Helvetica
'		FontColor red
'		FontSize 18
'		FontStyle bold
'		BackGroundColor GreenYellow
'		LineColor blue
'	}
'	separator {
'		LineColor red
'		BackGroundColor green
'		FontSize 16
'		FontStyle bold
'		FontColor purple
'	}
}
</style>
printscale daily zoom 2.7

Project starts 2023-09-21
[필요기술 사용법 터득] lasts 4 days
'[필요 기술 사용방법 터득] is colored in #DEECFC/darkblue
[shp 데이터를 면 레이어로 올림] lasts 4 days
[DB 설계] starts 2023-09-23
[DB 설계] lasts 4 days
[화면 설계] starts 2023-09-25
[화면 설계] lasts 3 days
'[화면 설계] is colored in #DEECFC/#333
[앱 지도 출력, 버튼 추가] starts 2023-09-25
[앱 지도 출력, 버튼 추가] lasts 3 days
'[앱 지도 출력, 버튼 추가] is colored in #B9CEEB/#333
'[앱 지도 출력, 버튼 추가] is colored in #B9CEEB/#333
'[차량 데이터를 점,선 레이어로 올림] is colored in #87A8D0/#333
'[차량 데이터를 점,선 레이어로 올림] is colored in #87A8D0/#333
[뷰 페이지 구현] starts 2023-09-25
[뷰 페이지 구현] lasts 4 days
[차량 데이터를 점,선으로 올림] starts 2023-09-25
[차량 데이터를 점,선으로 올림] lasts 4 days
'[뷰 페이지 구현] is colored in #C3B4D2/#333
[요구사항을 위한 자료수집, 통계 구현] starts 2023-09-28
[요구사항을 위한 자료수집, 통계 구현] lasts 5 days
[앱에서 HTTP 전송 반복 구현] starts 2023-09-28
[앱에서 HTTP 전송 반복 구현] lasts 5 days
[자바스크립트 달력 수정\n날짜/차량별 레이어 기능 추가] starts 2023-09-29
[자바스크립트 달력 수정\n날짜/차량별 레이어 기능 추가] lasts 5 days
[앱 소음,진동 \n데이터 측정 구현] starts 2023-10-03
[앱 소음,진동 \n데이터 측정 구현] lasts 3 days
'''
[실시간 GPS 기능 구현 시작\n실시간 좌표를 뷰페이지로] starts 2023-10-04
[실시간 GPS 기능 구현 시작\n실시간 좌표를 뷰페이지로] lasts 5  days
[앱 선 긋기 개선, csv 파일 생성] starts 2023-10-06
[앱 선 긋기 개선, csv 파일 생성] lasts 4 days
[앱의 정확한 좌표 요청] starts 2023-10-09
[앱의 정확한 좌표 요청] lasts 3 days
[날짜/차량별 측정기능\n지역구 레이어 분리] starts 2023-10-09
[날짜/차량별 측정기능\n지역구 레이어 분리] lasts 4 days
[뷰에서 선택한 날짜 반영] starts 2023-10-12
[뷰에서 선택한 날짜 반영] lasts 2 days
[csv 업로드 기능] starts 2023-10-12
[csv 업로드 기능] lasts 3 days
[실시간 경로지점 표시\nsld을 통한 스타일 지정] starts 2023-10-12
[실시간 경로지점 표시\nsld을 통한 스타일 지정] lasts 4 days
[통계에 쓰일 쿼리문 작성] starts 2023-10-13
[통계에 쓰일 쿼리문 작성] lasts 5 days
[앱csv 테스트] starts 2023-10-16
[앱csv 테스트] lasts 3 days
[통계 구현완료] starts 2023-10-17
[통계 구현완료] lasts 2 days



'[프로젝트 환경 설정] starts 2023-09-26
'[프로젝트 환경 설정] lasts 9 days
'[기초 뷰 구현] starts 2023-09-27
'[기초 뷰 구현] lasts 8 days
'[앱 개발] starts 2023-09-27
'[앱 개발] lasts 15 days
'[지도 경로 레이어 구현] starts 2023-09-27
'[지도 경로 레이어 구현] lasts 20 days
'[통계 데이터 출력 처리] starts 2023-09-27
'[통계 데이터 출력 처리] lasts 20 days
'프로젝트 시작일 9/22
'첫회의 9/25
'DB설계 9/22~9/27
'화면설계 9/22~9/27
'환경설정 9/26~10/4
'앱개발 9/26~10/11
'프론트엔드 ~10/4

@endgantt